In [26]:
import numpy as np


In [27]:
arr = np.array([1, 2, 3, 4, 5]) # 1D array
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) # 2D array
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]) # 3D array

In [28]:
# Elements in the array
print(arr.size)
print(arr2.size)
print(arr3.size)

print("\n")
# Dimensions of the array
print(arr.ndim)
print(arr2.ndim)
print(arr3.ndim)

5
6
8


1
2
3


In [29]:
print("Shape", arr.shape)

print("Reshaping the array")
arr.reshape(5, 1)

Shape (5,)
Reshaping the array


array([[1],
       [2],
       [3],
       [4],
       [5]])

In [30]:
arr_copy = arr.copy()
print("Original array:", arr)
print("Copied array:", arr_copy)

Original array: [1 2 3 4 5]
Copied array: [1 2 3 4 5]


In [31]:
demo = arr2.ravel()
print("Ravelled array:", demo)
demo[0] = 10
print("Modified ravelled array:", demo)

Ravelled array: [1 2 3 4 5 6]
Modified ravelled array: [10  2  3  4  5  6]


In [32]:
print(arr.sum()) # Sum of all elements in the array
print(arr2.sum(axis=1))  # Sum of each row in the array

15
[15 15]


In [33]:
#Broadcasting
print(arr*3) # Each element will be multiplied by 3

[ 3  6  9 12 15]


In [34]:
# Masking

print(arr[arr > 2]) # Elements greater > 2

[3 4 5]


In [35]:
# Where

print(np.where(arr > 2)) # positions of elements greater than 2

(array([2, 3, 4]),)


In [36]:
marks = np.array([67, 45, 23, 76, 98, 45, 98, 44, 90, 95, 34, 67, 65, 34, 89, 79, 87, 80, 76])

grades = np.select(
    [marks >= 90, marks >= 70, marks >= 50, marks >= 33],
    ["A", "B", "C", "D"],
    default="F"
)

print("Grades for the marks are:")
for mark, grade in zip(marks, grades):
    print(f"Mark: {mark} - Grade: {grade}")

Grades for the marks are:
Mark: 67 - Grade: C
Mark: 45 - Grade: D
Mark: 23 - Grade: F
Mark: 76 - Grade: B
Mark: 98 - Grade: A
Mark: 45 - Grade: D
Mark: 98 - Grade: A
Mark: 44 - Grade: D
Mark: 90 - Grade: A
Mark: 95 - Grade: A
Mark: 34 - Grade: D
Mark: 67 - Grade: C
Mark: 65 - Grade: C
Mark: 34 - Grade: D
Mark: 89 - Grade: B
Mark: 79 - Grade: B
Mark: 87 - Grade: B
Mark: 80 - Grade: B
Mark: 76 - Grade: B
